### ISSUE TITLE
Lock deployment's system dependencies

### ISSUE THREAD

**Issue by arthur-shaw** [arthur-shaw/draft_suso_course#33]
Namely:

- R
- Quarto

Consider doing this through a GitHub Actions (like in [adodown](https://github.com/lsms-worldbank/adodown/blob/main/.github/workflows/build_adodown_site.yaml)) that specifies versions of each:

```
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Build Site

jobs:
  adodown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          r-version: '4.2.2' # The R version to download (if necessary) and use.
          fetch-depth: 0

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.0.37 # Quarto version to download and use
```
