### ISSUE TITLE
Deploy SuSo training site via GitHub Actions

### ISSUE THREAD

**Issue by arthur-shaw** [arthur-shaw/draft_suso_course#34]
Let GitHub Pages Deploy Action post the site contents rather than me.

This way, I only track and post changes to qmd, R, and assets files

Use something like this:

```
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Build Site

jobs:
  adodown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          r-version: '4.2.2' # The R version to download (if necessary) and use.
          fetch-depth: 0

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.0.37 # Quarto version to download and use
```
